name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    env:
      PIP_DISABLE_PIP_VERSION_CHECK: 1
      PIP_NO_PYTHON_VERSION_WARNING: 1
      # Optional: some tools may use the key if present.
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      USER_AGENT: "GenAI-Tools/CI (no-contact@example.com)"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements*.txt', '**/dev-requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dev requirements (if present)
        run: |
          if [ -f "dev-requirements.txt" ]; then pip install -r dev-requirements.txt; fi
          if [ -f "requirements.txt" ]; then pip install -r requirements.txt; fi

      - name: Pre-commit (format & lint)
        run: |
          if [ -f ".pre-commit-config.yaml" ]; then
            pip install pre-commit
            pre-commit run --all-files || true
          fi

      - name: Lint top-level with flake8/black/isort (if available)
        run: |
          python - <<'PY'
import shutil, sys, subprocess
def run(cmd):
    try:
        print("+", " ".join(cmd)); subprocess.check_call(cmd)
    except FileNotFoundError:
        print("! Skipping (not installed):", cmd[0])
    except subprocess.CalledProcessError as e:
        print("! Lint step failed (non-blocking):", e); sys.exit(0)
for tool, args in (("flake8", ["."]), ("black", ["--check", "."]), ("isort", ["--check-only", "."])):
    run([tool] + args)
PY

      - name: Install & test each tool
        shell: bash
        run: |
          set -e
          echo "Scanning tools/ for subprojects..."
          if [ ! -d "tools" ]; then
            echo "No tools/ directory found. Skipping."
            exit 0
          fi
          for d in tools/*; do
            [ -d "$d" ] || continue
            echo "::group::Processing $d"
            if [ -f "$d/requirements.txt" ]; then
              echo "Installing $d requirements..."
              pip install -r "$d/requirements.txt"
            fi

            echo "Static lint (non-blocking) for $d"
            flake8 "$d" || true

            if compgen -G "$d/tests/*.py" > /dev/null; then
              echo "Running pytest for $d..."
              pytest -q "$d/tests" || true
            else
              echo "No tests found for $d, performing import smoke checks (if app.py exists)..."
              if [ -f "$d/app.py" ]; then
                python -m py_compile "$d/app.py" || true
              fi
            fi
            echo "::endgroup::"
          done

      - name: Summarize
        run: |
          echo "✅ CI completed for Python ${{ matrix.python-version }}"
